---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  labels:
    app: orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders 
  template:
    metadata:
      labels:
        app: orders 
    spec:
      containers:
      - name: orders-container
        image: orders:latest
        ports:
        - containerPort: 8081
        env:
        - name: DATABASE_URL
          value: "postgres://orders_user:orders_pass@orders_db:5432/orders_db?sslmode=disable"