services:
  orders:
    image: orders
    ports:
      - "8082:8082"
    networks:
      - shared
    environment:
      USER_SERVICE_URL: http://users:8080
      ITEM_SERVICE_URL: http://items:8081
  items:
    image: items 
    networks:
      - shared
  users:
    image: users 
    networks:
      - shared
  
networks:
  shared: {}